# Generated by Django 5.2.1 on 2025-05-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(default='AlphaSense', max_length=255)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('download_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('file_directory', models.CharField(blank=True, max_length=1000, null=True)),
                ('raw_companies', models.CharField(blank=True, max_length=1000, null=True)),
                ('raw_company_count', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_author', models.CharField(blank=True, max_length=1000, null=True)),
                ('raw_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('raw_page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('parsed_ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('report_type', models.CharField(blank=True, max_length=255, null=True)),
                ('report_summary', models.JSONField(blank=True, null=True)),
                ('file_download_time', models.DateTimeField(blank=True, null=True)),
                ('file_update_time', models.DateTimeField(blank=True, null=True)),
                ('file_summary_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Not Downloaded'), (1, 'Downloaded'), (2, 'Preprocessed'), (3, 'Summarized')], default=0)),
            ],
            options={
                'ordering': ['-file_download_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchNoteIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('research_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='research_summaries.researchnote')),
            ],
        ),
    ]
