# Generated by Django 5.2.1 on 2025-06-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchnote',
            name='is_advanced_summary',
            field=models.BooleanField(default=False, help_text='Whether advanced summarization was used'),
        ),
        migrations.AddField(
            model_name='researchnote',
            name='is_vectorized',
            field=models.BooleanField(default=False, help_text='Whether this note has been added to a vector store'),
        ),
        migrations.AddField(
            model_name='researchnote',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Date extracted from PDF filename', null=True),
        ),
        migrations.AddField(
            model_name='researchnote',
            name='vector_group_id',
            field=models.PositiveIntegerField(blank=True, help_text='Vector database group assignment', null=True),
        ),
        migrations.AlterField(
            model_name='researchnote',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Not Downloaded'), (1, 'Downloaded'), (2, 'Preprocessed'), (3, 'Summarized'), (10, 'Error 1'), (11, 'Error 2')], default=0),
        ),
        migrations.AddIndex(
            model_name='researchnote',
            index=models.Index(fields=['parsed_ticker', '-publication_date'], name='research_su_parsed__cd5d71_idx'),
        ),
        migrations.AddIndex(
            model_name='researchnote',
            index=models.Index(fields=['vector_group_id'], name='research_su_vector__87ae38_idx'),
        ),
        migrations.AddIndex(
            model_name='researchnote',
            index=models.Index(fields=['is_vectorized'], name='research_su_is_vect_222654_idx'),
        ),
        migrations.AddIndex(
            model_name='researchnote',
            index=models.Index(fields=['status', '-file_download_time'], name='research_su_status_1196c0_idx'),
        ),
    ]
