# Generated by Django 5.2.1 on 2025-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_summaries', '0002_researchnote_is_advanced_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchnote',
            name='file_hash_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='researchnote',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Not Downloaded'), (1, 'Downloaded'), (2, 'Preprocessed'), (3, 'Summarized'), (4, 'Advanced Summarized'), (10, 'Error 1'), (11, 'Error 2')], default=0),
        ),
    ]
