# Generated by Django 5.2.1 on 2025-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_summaries', '0003_researchnote_file_hash_id_alter_researchnote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchnote',
            name='openai_file_id',
            field=models.CharField(blank=True, help_text='OpenAI file ID for reuse', max_length=255, null=True),
        ),
    ]
