# Generated by Django 5.2.1 on 2025-07-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_summaries', '0004_researchnote_openai_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchnote',
            name='is_persistent_document',
            field=models.BooleanField(default=False, help_text='Whether this is an evergreen/persistent document (True) or standard/temporary (False)'),
        ),
        migrations.AddIndex(
            model_name='researchnote',
            index=models.Index(fields=['is_persistent_document'], name='research_su_is_pers_8bd265_idx'),
        ),
    ]
