# Generated by Django 5.2.1 on 2025-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_summaries', '0005_researchnote_is_persistent_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchnote',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Not Downloaded'), (1, 'Downloaded'), (2, 'Preprocessed'), (3, 'Summarized'), (4, 'Advanced Summarized'), (10, 'Error 1'), (11, 'Error 2'), (12, 'Testing')], default=0),
        ),
    ]
