# Generated by Django 5.2.1 on 2025-08-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_summaries', '0006_alter_researchnote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchnote',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this document is still in an Agent'),
        ),
    ]
