# Generated by Django 5.2.1 on 2025-07-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_ticker', models.CharField(max_length=10)),
                ('full_ticker', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('sub_industry', models.CharField(max_length=255)),
                ('vector_id', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_tickers',
                'ordering': ['main_ticker'],
                'indexes': [models.Index(fields=['main_ticker'], name='stock_ticke_main_ti_477c8f_idx'), models.Index(fields=['vector_id'], name='stock_ticke_vector__28732a_idx')],
                'unique_together': {('main_ticker', 'vector_id')},
            },
        ),
    ]
