# Generated by Django 5.2.1 on 2025-08-17 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='file_retention',
            field=models.PositiveIntegerField(default=730, help_text='File retention period in days (default: 2 years = 730 days)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(109500)]),
        ),
    ]
