# Generated by Django 5.2.1 on 2025-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_knowledgebase_file_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='purpose',
            field=models.IntegerField(choices=[(0, 'Industry'), (1, 'User')], default=0, help_text='Purpose of this knowledge base'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['purpose'], name='agents_know_purpose_6b9b83_idx'),
        ),
    ]
