# Generated by Django 5.2.1 on 2025-07-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cik', models.CharField(max_length=10)),
                ('accession', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=260)),
                ('file_id', models.CharField(max_length=100)),
                ('vector_group_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'processed_files',
                'indexes': [models.Index(fields=['cik', 'accession'], name='processed_f_cik_1d11a1_idx'), models.Index(fields=['file_id'], name='processed_f_file_id_bb9e82_idx')],
                'unique_together': {('cik', 'accession', 'filename', 'vector_group_id')},
            },
        ),
        migrations.CreateModel(
            name='ProcessedFiling',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cik', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=12)),
                ('accession', models.CharField(max_length=20)),
                ('filing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processed',
                'ordering': ['-filing_date'],
                'indexes': [models.Index(fields=['cik', 'accession'], name='processed_cik_783a5e_idx'), models.Index(fields=['ticker'], name='processed_ticker_35ed06_idx')],
                'unique_together': {('cik', 'accession')},
            },
        ),
    ]
