# Generated by Django 5.2.1 on 2025-10-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDGAR_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=12, unique=True)),
                ('earnings_date', models.DateField(blank=True, null=True)),
                ('cik', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'watchlist',
                'ordering': ['ticker'],
                'indexes': [models.Index(fields=['ticker'], name='watchlist_ticker_5aff55_idx'), models.Index(fields=['earnings_date'], name='watchlist_earning_0eaba0_idx'), models.Index(fields=['is_active'], name='watchlist_is_acti_8f7f73_idx')],
            },
        ),
    ]
