# Generated by Django 5.2.1 on 2025-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_read_time_advanced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
