# Generated by Django 5.2.1 on 2025-07-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_read_time_advanced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_view_uploads', 'Can view uploads'), ('can_view_research_summaries', 'Can view research summaries'), ('can_view_agents', 'Can view agents')], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
