# Generated by Django 5.2.1 on 2025-08-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_read_time_expert',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
