# Generated by Django 5.2.1 on 2025-07-10 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_directory', models.CharField(help_text="S3 directory path (e.g., 'ResearchNotes', 'UserDocuments')", max_length=255)),
                ('file_hash_id', models.CharField(help_text='SHA-256 hash of file content for deduplication', max_length=64, unique=True)),
                ('openai_file_id', models.CharField(blank=True, help_text='OpenAI file ID after upload', max_length=100, null=True)),
                ('vector_group_id', models.PositiveIntegerField(blank=True, help_text='Links to KnowledgeBase.vector_group_id', null=True)),
                ('filename', models.CharField(help_text='Original filename', max_length=500)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the file was uploaded')),
                ('publication_date', models.DateField(blank=True, help_text='Document publication date (if applicable)', null=True)),
                ('is_vectorized', models.BooleanField(default=False, help_text='Whether this document has been added to a vector store')),
                ('report_type', models.CharField(default='general', help_text='Type of document (free text)', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (extracted text, page count, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-upload_date', '-created_at'],
                'indexes': [models.Index(fields=['file_hash_id'], name='documents_d_file_ha_78db58_idx'), models.Index(fields=['vector_group_id'], name='documents_d_vector__436e08_idx'), models.Index(fields=['is_vectorized'], name='documents_d_is_vect_e1ba90_idx'), models.Index(fields=['report_type'], name='documents_d_report__7cce70_idx'), models.Index(fields=['-upload_date'], name='documents_d_upload__9d8ae1_idx')],
            },
        ),
    ]
