# Generated by Django 5.2.1 on 2025-07-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('file_hash_id', 'vector_group_id')},
        ),
    ]
