# Generated by Django 5.2.1 on 2025-07-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_persistent_document',
            field=models.BooleanField(default=False, help_text='Whether this is an evergreen/persistent document (True) or standard/temporary (False)'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_persistent_document'], name='documents_d_is_pers_f24f4e_idx'),
        ),
    ]
