# Generated by Django 5.2.1 on 2025-07-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_is_persistent_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_hash_id',
            field=models.CharField(help_text='SHA-256 hash of file content for deduplication', max_length=64),
        ),
    ]
