# Generated by Django 5.2.1 on 2025-07-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file_hash_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_is_pers_f24f4e_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='expiration_rule',
            field=models.PositiveIntegerField(choices=[(0, 'Standard'), (1, 'Evergreen'), (2, 'Temporary')], default=0, help_text='Document expiration rule: 0=Standard, 1=Evergreen, 2=Temporary'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiration_rule'], name='documents_d_expirat_a023bd_idx'),
        ),
    ]
