# Generated by Django 5.2.1 on 2025-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this document is still active'),
        ),
    ]
